import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";
import home from "../public/home.jpg";
export default function Home() {
  return (
    <div className="flex align-center justify-center">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Image src={home} />
    </div>
  );
}
